"""Initial schema

Revision ID: f3f9a776b0c5
Revises: 
Create Date: 2026-10-08 22:51:10.132073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.vitals.models


# revision identifiers, used by Alembic.
revision: str = 'f3f9a776b0c5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_number', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('sex', sa.String(length=20), nullable=True),
    sa.Column('marital_status', sa.String(length=30), nullable=True),
    sa.Column('religion', sa.String(length=30), nullable=True),
    sa.Column('occupation', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=250), nullable=True),
    sa.Column('phone_number', sa.String(length=30), nullable=True),
    sa.Column('blood_group', sa.String(length=5), nullable=True),
    sa.Column('genotype', sa.String(length=5), nullable=True),
    sa.Column('allergy_status', sa.String(length=30), nullable=False),
    sa.Column('allergy_details', sa.String(length=250), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_number')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('next_of_kins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('relationship', sa.String(length=50), nullable=False),
    sa.Column('phone_number', sa.String(length=30), nullable=False),
    sa.Column('address', sa.String(length=250), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('facility_id', 'name', name='uq_ward_facility_name')
    )
    op.create_table('beds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ward_id', sa.Integer(), nullable=False),
    sa.Column('bed_number', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ward_id'], ['wards.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ward_id', 'bed_number', name='uq_bed_ward_number')
    )
    op.create_table('admissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admission_number', sa.String(length=30), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('ward_id', sa.Integer(), nullable=False),
    sa.Column('bed_id', sa.Integer(), nullable=False),
    sa.Column('admitted_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('reason_for_admission', sa.String(length=500), nullable=False),
    sa.Column('presenting_complaint', sa.String(length=500), nullable=True),
    sa.Column('patient_account', sa.String(length=1000), nullable=True),
    sa.Column('doctor_assessment', sa.String(length=2000), nullable=True),
    sa.Column('nursing_assessment', sa.String(length=2000), nullable=True),
    sa.Column('nursing_diagnosis', sa.String(length=2000), nullable=True),
    sa.Column('admitted_by', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('discharged_at', sa.DateTime(), nullable=True),
    sa.Column('discharge_summary', sa.String(length=2000), nullable=True),
    sa.Column('discharged_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admitted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['bed_id'], ['beds.id'], ),
    sa.ForeignKeyConstraint(['discharged_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['ward_id'], ['wards.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admission_number')
    )
    op.create_table('clinical_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admission_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('note_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.String(length=3000), nullable=False),
    sa.Column('plan', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admission_id'], ['admissions.id'], ),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('investigation_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admission_id', sa.Integer(), nullable=False),
    sa.Column('test_name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('ordered_by', sa.Integer(), nullable=False),
    sa.Column('ordered_at', sa.DateTime(), nullable=False),
    sa.Column('urgency', sa.String(length=20), nullable=False),
    sa.Column('clinical_indication', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admission_id'], ['admissions.id'], ),
    sa.ForeignKeyConstraint(['ordered_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medication_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admission_id', sa.Integer(), nullable=False),
    sa.Column('medication_name', sa.String(length=150), nullable=False),
    sa.Column('dose', sa.String(length=100), nullable=False),
    sa.Column('route', sa.String(length=50), nullable=False),
    sa.Column('frequency', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('prescribed_by', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('created_at', app.vitals.models.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.vitals.models.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admission_id'], ['admissions.id'], ),
    sa.ForeignKeyConstraint(['prescribed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medication_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medication_orders_admission_id'), ['admission_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medication_orders_prescribed_by'), ['prescribed_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_medication_orders_status'), ['status'], unique=False)

    op.create_table('vital_signs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admission_id', sa.Integer(), nullable=False),
    sa.Column('recorded_by', sa.Integer(), nullable=False),
    sa.Column('recorded_at', app.vitals.models.UTCDateTime(), nullable=False),
    sa.Column('systolic_bp', sa.Integer(), nullable=True),
    sa.Column('diastolic_bp', sa.Integer(), nullable=True),
    sa.Column('pulse', sa.Integer(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('respiratory_rate', sa.Integer(), nullable=True),
    sa.Column('spo2', sa.Float(), nullable=True),
    sa.Column('measurement_status', sa.String(length=30), nullable=False),
    sa.Column('not_measured_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', app.vitals.models.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admission_id'], ['admissions.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vital_signs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vital_signs_admission_id'), ['admission_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vital_signs_recorded_at'), ['recorded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_vital_signs_recorded_by'), ['recorded_by'], unique=False)

    op.create_table('investigation_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investigation_order_id', sa.Integer(), nullable=False),
    sa.Column('recorded_by', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('result_value', sa.String(length=1000), nullable=False),
    sa.Column('reference_range', sa.String(length=100), nullable=True),
    sa.Column('is_abnormal', sa.Boolean(), nullable=False),
    sa.Column('critical_alert', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['investigation_order_id'], ['investigation_orders.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medication_administrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medication_order_id', sa.Integer(), nullable=False),
    sa.Column('administered_by', sa.Integer(), nullable=False),
    sa.Column('administered_at', app.vitals.models.UTCDateTime(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('not_administered_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', app.vitals.models.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.vitals.models.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['administered_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['medication_order_id'], ['medication_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medication_administrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medication_administrations_administered_by'), ['administered_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_medication_administrations_medication_order_id'), ['medication_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medication_administrations_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medication_administrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medication_administrations_status'))
        batch_op.drop_index(batch_op.f('ix_medication_administrations_medication_order_id'))
        batch_op.drop_index(batch_op.f('ix_medication_administrations_administered_by'))

    op.drop_table('medication_administrations')
    op.drop_table('investigation_results')
    with op.batch_alter_table('vital_signs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vital_signs_recorded_by'))
        batch_op.drop_index(batch_op.f('ix_vital_signs_recorded_at'))
        batch_op.drop_index(batch_op.f('ix_vital_signs_admission_id'))

    op.drop_table('vital_signs')
    with op.batch_alter_table('medication_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medication_orders_status'))
        batch_op.drop_index(batch_op.f('ix_medication_orders_prescribed_by'))
        batch_op.drop_index(batch_op.f('ix_medication_orders_admission_id'))

    op.drop_table('medication_orders')
    op.drop_table('investigation_orders')
    op.drop_table('clinical_notes')
    op.drop_table('admissions')
    op.drop_table('beds')
    op.drop_table('wards')
    op.drop_table('next_of_kins')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_table('patients')
    op.drop_table('facilities')
    # ### end Alembic commands ###
